import type { OrderRollGroup } from '../types';
import type { OperatorRuntimeState } from './types';

const operatorA17RollGroups: OrderRollGroup[] = [
  {
    id: 'a17-main',
    title: 'Группа 1',
    filmType: 'рукав',
    micron: '80 мкм',
    color: 'Прозрачный',
    sizeMeters: '1200 м x 1.2 м',
    sleeve: '76 мм',
    recipe: '80% первичка / 20% вторичка',
    recipeVersion: 'v3.2',
    plannedRolls: 2,
    plannedNetKg: 41.2,
    tolerancePercent: 2,
    machine: 'Экструдер E-04',
    owner: 'Оператор линии',
    status: 'Готово к выпуску',
    rollIds: ['R-A17-01', 'R-A17-02'],
  },
  {
    id: 'a17-marked',
    title: 'Группа 2',
    filmType: 'рукав',
    micron: '80 мкм',
    color: 'Прозрачный с маркировкой',
    sizeMeters: '900 м x 1.2 м',
    sleeve: '102 мм',
    recipe: 'М2 для оставшегося рулона',
    recipeVersion: 'v3.3',
    plannedRolls: 1,
    plannedNetKg: 36.8,
    tolerancePercent: 2,
    machine: 'Экструдер E-04',
    owner: 'Оператор линии',
    status: 'Изменение рецепта на остаток',
    appliesFromRollSequence: 3,
    rollIds: ['R-A17-03'],
  },
];

const operatorB11RollGroups: OrderRollGroup[] = [
  {
    id: 'b11-main',
    title: 'Группа 1',
    filmType: 'пленка',
    micron: '60 мкм',
    color: 'Молочный',
    sizeMeters: '800 м x 1.0 м',
    sleeve: '76 мм',
    recipe: '70% первичка / 30% вторичка',
    recipeVersion: 'v2.8',
    plannedRolls: 2,
    plannedNetKg: 35,
    tolerancePercent: 2,
    machine: 'Экструдер E-02',
    owner: 'Оператор линии',
    status: 'Готово к выпуску',
    rollIds: ['R-B11-01', 'R-B11-02'],
  },
];

const operatorC04RollGroups: OrderRollGroup[] = [
  {
    id: 'c04-main',
    title: 'Остаток заказа',
    filmType: 'пакет',
    micron: '35 мкм',
    color: 'Прозрачный',
    sizeMeters: '500 м x 0.8 м',
    sleeve: '76 мм',
    recipe: '60% первичка / 40% вторичка',
    recipeVersion: 'v1.9',
    plannedRolls: 30,
    plannedNetKg: 10,
    tolerancePercent: 2,
    machine: 'Экструдер E-04',
    owner: 'Оператор линии',
    status: 'Отложен с рулона 16',
    rollIds: ['R-C04-16', 'R-C04-17'],
  },
];

const operatorE12RollGroups: OrderRollGroup[] = [
  {
    id: 'e12-main',
    title: 'Группа 1',
    filmType: 'рукав',
    micron: '70 мкм',
    color: 'Прозрачный',
    sizeMeters: '1000 м x 1.1 м',
    sleeve: '76 мм',
    recipe: '75% первичка / 25% вторичка',
    recipeVersion: 'v4.1',
    plannedRolls: 3,
    plannedNetKg: 39.5,
    tolerancePercent: 2,
    machine: 'Экструдер E-05',
    owner: 'Оператор линии',
    status: 'Передано на склад',
    rollIds: ['R-E12-01', 'R-E12-02', 'R-E12-03'],
  },
];

export const initialOperatorRuntime: OperatorRuntimeState = {
  shift: {
    id: 'OPERATOR-SHIFT-01',
    status: 'active',
    operatorName: 'Оператор линии',
    workplace: 'Экструдер E-04',
    defaultMachineId: 'E-04',
    defaultMachineLabel: 'Экструдер E-04',
    shiftCapacityMinutes: 480,
    remainingShiftMinutes: 310,
    bigBagId: 'BB-E04-06',
    bigBagQrCode: 'QR-BB-E04-06',
    startKg: 700,
    expectedEndKg: 476.4,
    plannedUsageKg: 223.6,
    lastActorLabel: 'Оператор линии',
    weightSource: 'manual_after_physical_weighing',
    enteredBy: 'Оператор линии',
    enteredAt: '08:00',
  },
  orders: [
    {
      id: 'OP-2606-032',
      title: 'Заказ A-17',
      orderId: 'A-17',
      customerAlias: 'Клиент A-17',
      templateName: 'Рукав 80',
      filmType: 'рукав',
      cardSizeMeters: '1200 м',
      status: 'assigned',
      state: 'new',
      lastEventAt: '10:25',
      workplace: 'Экструдер E-04',
      problemCount: 0,
      plannedRolls: 3,
      completedRolls: 0,
      deferredRolls: 0,
      currentRoll: 1,
      rollProgress: { current: 1, completed: 0, total: 3 },
      plannedNetKg: 123.6,
      rollPlanKg: 41.2,
      materialRecipe: '80% первичка / 20% вторичка',
      realMicron: '80 мкм',
      sizeMeters: '1200 м x 1.2 м',
      rollGroups: operatorA17RollGroups,
      rolls: [
        { id: 'R-A17-01', dispatchItemId: 'PRD-R-A17-01', sequenceNumber: 1, queueRank: 10, orderNumber: 'A-17', machineId: 'E-04', machineLabel: 'Экструдер E-04', priority: 'срочно', estimatedMinutes: 95, meterageMeters: 1200, groupId: 'a17-main', status: 'не принят', plannedNetKg: 41.2, toleranceState: 'pending', recipeVersion: 'v3.2', labelState: 'not_printed', warehouseState: 'not_ready' },
        { id: 'R-A17-02', dispatchItemId: 'PRD-R-A17-02', sequenceNumber: 2, queueRank: 20, orderNumber: 'A-17', machineId: 'E-04', machineLabel: 'Экструдер E-04', priority: 'срочно', estimatedMinutes: 95, meterageMeters: 1200, groupId: 'a17-main', status: 'не принят', plannedNetKg: 41.2, toleranceState: 'pending', recipeVersion: 'v3.2', labelState: 'not_printed', warehouseState: 'not_ready' },
        { id: 'R-A17-03', dispatchItemId: 'PRD-R-A17-03', sequenceNumber: 3, queueRank: 30, orderNumber: 'A-17', machineId: 'E-02', machineLabel: 'Экструдер E-02', priority: 'срочно', estimatedMinutes: 78, meterageMeters: 900, groupId: 'a17-marked', status: 'не принят', plannedNetKg: 36.8, toleranceState: 'pending', recipeVersion: 'v3.3', labelState: 'not_printed', warehouseState: 'not_ready' },
      ],
    },
    {
      id: 'OP-2606-033',
      title: 'Заказ B-11',
      orderId: 'B-11',
      customerAlias: 'Клиент B-11',
      templateName: 'Пленка 60',
      filmType: 'пленка',
      cardSizeMeters: '800 м',
      status: 'assigned',
      state: 'new',
      lastEventAt: '09:58',
      workplace: 'Экструдер E-02',
      problemCount: 0,
      plannedRolls: 2,
      completedRolls: 0,
      deferredRolls: 0,
      currentRoll: 1,
      rollProgress: { current: 1, completed: 0, total: 2 },
      plannedNetKg: 70,
      rollPlanKg: 35,
      materialRecipe: '70% первичка / 30% вторичка',
      realMicron: '60 мкм',
      sizeMeters: '800 м x 1.0 м',
      rollGroups: operatorB11RollGroups,
      rolls: [
        { id: 'R-B11-01', dispatchItemId: 'PRD-R-B11-01', sequenceNumber: 1, queueRank: 50, orderNumber: 'B-11', machineId: 'E-02', machineLabel: 'Экструдер E-02', priority: 'обычный', estimatedMinutes: 82, meterageMeters: 800, groupId: 'b11-main', status: 'не принят', plannedNetKg: 35, toleranceState: 'pending', recipeVersion: 'v2.8', labelState: 'not_printed', warehouseState: 'not_ready' },
        { id: 'R-B11-02', dispatchItemId: 'PRD-R-B11-02', sequenceNumber: 2, queueRank: 60, orderNumber: 'B-11', machineId: 'E-02', machineLabel: 'Экструдер E-02', priority: 'обычный', estimatedMinutes: 82, meterageMeters: 800, groupId: 'b11-main', status: 'не принят', plannedNetKg: 35, toleranceState: 'pending', recipeVersion: 'v2.8', labelState: 'not_printed', warehouseState: 'not_ready' },
      ],
    },
    {
      id: 'OP-2606-034',
      title: 'Заказ C-04',
      orderId: 'C-04',
      customerAlias: 'Клиент C-04',
      templateName: 'Пакет 35',
      filmType: 'пакет',
      cardSizeMeters: '500 м',
      status: 'deferred',
      state: 'deferred',
      lastEventAt: '11:05',
      workplace: 'Экструдер E-04',
      problemCount: 0,
      plannedRolls: 30,
      completedRolls: 15,
      deferredRolls: 15,
      currentRoll: 16,
      rollProgress: { current: 16, completed: 15, total: 30 },
      plannedNetKg: 300,
      rollPlanKg: 10,
      materialRecipe: '60% первичка / 40% вторичка',
      realMicron: '35 мкм',
      sizeMeters: '500 м x 0.8 м',
      rollGroups: operatorC04RollGroups,
      rolls: [
        { id: 'R-C04-16', dispatchItemId: 'PRD-R-C04-16', sequenceNumber: 16, queueRank: 70, orderNumber: 'C-04', machineId: 'E-04', machineLabel: 'Экструдер E-04', priority: 'обычный', estimatedMinutes: 38, meterageMeters: 500, groupId: 'c04-main', status: 'отложен: следующий', plannedNetKg: 10, toleranceState: 'pending', recipeVersion: 'v1.9', labelState: 'not_printed', warehouseState: 'not_ready' },
        { id: 'R-C04-17', dispatchItemId: 'PRD-R-C04-17', sequenceNumber: 17, queueRank: 80, orderNumber: 'C-04', machineId: 'E-04', machineLabel: 'Экструдер E-04', priority: 'обычный', estimatedMinutes: 38, meterageMeters: 500, groupId: 'c04-main', status: 'отложен', plannedNetKg: 10, toleranceState: 'pending', recipeVersion: 'v1.9', labelState: 'not_printed', warehouseState: 'not_ready' },
      ],
    },
    {
      id: 'OP-2606-036',
      title: 'Заказ E-12',
      orderId: 'E-12',
      customerAlias: 'Клиент E-12',
      templateName: 'Рукав 70',
      filmType: 'рукав',
      cardSizeMeters: '1000 м',
      status: 'warehouse',
      state: 'warehouse',
      lastEventAt: '12:18',
      workplace: 'Экструдер E-05',
      problemCount: 0,
      plannedRolls: 3,
      completedRolls: 3,
      deferredRolls: 0,
      currentRoll: 3,
      rollProgress: { current: 3, completed: 3, total: 3 },
      plannedNetKg: 118.5,
      rollPlanKg: 39.5,
      materialRecipe: '75% первичка / 25% вторичка',
      realMicron: '70 мкм',
      sizeMeters: '1000 м x 1.1 м',
      rollGroups: operatorE12RollGroups,
      rolls: [
        { id: 'R-E12-01', dispatchItemId: 'PRD-R-E12-01', sequenceNumber: 1, queueRank: 90, orderNumber: 'E-12', machineId: 'E-05', machineLabel: 'Экструдер E-05', priority: 'обычный', estimatedMinutes: 76, meterageMeters: 1000, groupId: 'e12-main', status: 'передан на склад', plannedNetKg: 39.5, actualNetKg: 39.6, spoolKg: 1.8, grossKg: 41.4, toleranceState: 'within', recipeVersion: 'v4.1', qrCode: 'QR-R-E12-01', labelState: 'verified', warehouseState: 'sent', sentToWarehouseAt: '2026-07-04 13:22' },
        { id: 'R-E12-02', dispatchItemId: 'PRD-R-E12-02', sequenceNumber: 2, queueRank: 100, orderNumber: 'E-12', machineId: 'E-05', machineLabel: 'Экструдер E-05', priority: 'обычный', estimatedMinutes: 76, meterageMeters: 1000, groupId: 'e12-main', status: 'принят складом', plannedNetKg: 39.5, actualNetKg: 39.4, spoolKg: 1.8, grossKg: 41.2, toleranceState: 'within', recipeVersion: 'v4.1', qrCode: 'QR-R-E12-02', labelState: 'verified', warehouseState: 'received', sentToWarehouseAt: '2026-07-05 11:40' },
        { id: 'R-E12-03', dispatchItemId: 'PRD-R-E12-03', sequenceNumber: 3, queueRank: 110, orderNumber: 'E-12', machineId: 'E-05', machineLabel: 'Экструдер E-05', priority: 'обычный', estimatedMinutes: 76, meterageMeters: 1000, groupId: 'e12-main', status: 'выдан со склада', plannedNetKg: 39.5, actualNetKg: 39.7, spoolKg: 1.8, grossKg: 41.5, toleranceState: 'within', recipeVersion: 'v4.1', qrCode: 'QR-R-E12-03', labelState: 'verified', warehouseState: 'delivered', sentToWarehouseAt: '2026-07-06 12:18' },
      ],
    },
  ],
  audit: {
    'OP-2606-032': [
      { id: 'a-op-a17', objectId: 'OP-2606-032', time: '10:25', actorLabel: 'Зав. производства', actionLabel: 'Заказ назначен', detail: 'Заказ доступен оператору после открытия смены.' },
    ],
    'OP-2606-033': [
      { id: 'a-op-b11', objectId: 'OP-2606-033', time: '09:58', actorLabel: 'Зав. производства', actionLabel: 'Заказ назначен', detail: 'Ожидает принятия оператором.' },
    ],
    'OP-2606-034': [
      { id: 'a-op-c04', objectId: 'OP-2606-034', time: '11:05', actorLabel: 'Оператор', actionLabel: 'Заказ отложен', detail: 'Выполнено 15 из 30 рулонов, остаток сохранен.' },
    ],
    'OP-2606-036': [
      { id: 'a-op-e12', objectId: 'OP-2606-036', time: '12:18', actorLabel: 'Оператор', actionLabel: 'передано на склад', detail: 'Рулоны E-12 переданы в складскую приемку по QR.' },
    ],
  },
};
