/**
 * Domain event vocabulary — ТЗ §7 ("Events vocabulary").
 *
 * Backend may rename events, but MUST preserve the business fact, actor,
 * object, reason/evidence and visibility (ТЗ §7 preamble). Events are durable
 * facts that back audit and dashboards (ТЗ §5.6, §11).
 *
 * `family` groups events for the /api/events?family=... filter.
 */

export const EVENT_FAMILIES = [
  'audit',
  'problem',
  'notification',
  'device',
  'admin',
  'integration',
  'gateway',
] as const;
export type EventFamily = (typeof EVENT_FAMILIES)[number];

export const DOMAIN_EVENTS = [
  // commercial / correction
  'audit:commercial_recipe_snapshot_set',
  'audit:raw_material_definition_created',
  'audit:recipe_definition_created',
  'audit:commercial_counterparty_created',
  'audit:counterparty_template_created',
  'audit:counterparty_template_updated',
  'audit:counterparty_template_applied',
  'audit:stock_production_template_created',
  'audit:stock_production_template_updated',
  'audit:stock_production_template_applied',
  'audit:production_lead_request_created',
  'audit:production_request_created_on_behalf_of_commercial',
  'problem:production_reported_to_commercial',
  'notification:commercial_problem_received',
  'notification:commercial_action_required',
  'notification:commercial_order_ready_for_shipment',
  'audit:production_problem_seen_by_commercial',
  'audit:commercial_position_updated',
  'audit:commercial_finance_note_updated',
  'audit:commercial_order_comment_updated',
  'audit:commercial_order_amended',
  'audit:commercial_amendment_reconciled',
  'audit:commercial_order_cancelled',
  'audit:commercial_order_reactivated',
  'notification:commercial_order_amended',
  'notification:commercial_order_cancelled',
  'notification:commercial_order_reactivated',
  'audit:commercial_position_correction_requested',
  'audit:correction_applies_from_roll_set',
  'audit:current_roll_resolution_set',
  'audit:recipe_correction_applied',
  'notification:commercial_correction_applied',
  'notification:operator_recipe_changed',
  'audit:commercial_draft_promoted',
  'audit:commercial_order_deleted',
  'audit:invoice_handoff_created',

  // production / operator
  'audit:task_assigned',
  'audit:task_reassigned',
  'audit:machine_assigned',
  'audit:operator_shift_machine_assigned',
  'audit:operator_machine_change_requested',
  'audit:operator_machine_change_final_weight_recorded',
  'audit:operator_machine_change_ready',
  'audit:operator_machine_change_completed',
  'audit:operator_machine_change_cancelled',
  'audit:operator_shift_machine_assignment_cancelled',
  'notification:operator_machine_change_requested',
  'notification:operator_machine_change_ready',
  'notification:operator_machine_change_completed',
  'notification:operator_machine_change_cancelled',
  'problem:machine_breakdown_reported',
  'audit:operator_machine_breakdown_reassigned',
  // поломка станка: жизненный цикл сломан → в ремонте → исправен (дизайн 2026-07-14)
  'audit:machine_breakdown_confirmed',
  'audit:machine_breakdown_rejected',
  'audit:machine_repair_started',
  'audit:machine_repaired',
  // брак, зафиксированный завпроизводства при визуальном контроле (дизайн 2026-07-14)
  'problem:production_defect_reported',
  'audit:replacement_roll_created',
  'audit:roll_dispatch_assigned',
  'audit:roll_dispatch_bulk_assigned',
  'audit:operator_roll_accepted',
  'audit:operator_roll_handed_over',
  'notification:production_order_fully_handed_over',
  'audit:production_priority_changed',
  'audit:production_queue_reordered',
  'audit:production_order_created',
  'audit:production_order_approved',
  'audit:bigbag_scan_recorded',
  'audit:bigbag_weight_recorded',
  'device.scale.offline',
  'device.scan.offline',
  'device.scan.mismatch',
  'audit:label_reprint_requested',
  'audit:operator_weight_captured',
  'audit:operator_roll_reweighed',
  'audit:operator_roll_step_reopened',
  'audit:operator_weight_capture_failed',
  'audit:operator_label_print_requested',
  'audit:operator_label_print_submitted',
  'audit:operator_label_print_failed',
  'audit:operator_label_print_delivery_unknown',
  'audit:operator_label_print_reconciled',
  'audit:operator_qr_verified',
  'audit:operator_physical_operation_recovered',
  'audit:defect_recorded',
  'audit:defect_spool_returned',
  'audit:warehouse_reserve_roll_created',
  'audit:defect_bag_weighed',
  'audit:defect_bag_label_print_requested',
  'audit:defect_bag_label_reprint_requested',
  'audit:defect_bag_label_print_submitted',
  'audit:defect_bag_label_print_failed',
  'audit:defect_bag_label_print_delivery_unknown',
  'audit:defect_bag_label_print_reconciled',

  // operator shift with big bags + balance check (design 2026-07-13)
  'audit:bigbag_created',
  'audit:bigbag_label_print_requested',
  'audit:bigbag_label_reprint_requested',
  'audit:bigbag_label_print_submitted',
  'audit:bigbag_label_print_failed',
  'audit:bigbag_label_print_delivery_unknown',
  'audit:bigbag_label_print_reconciled',
  'audit:bigbag_registration_confirmed',
  'audit:bigbag_moved_to_production',
  'audit:bigbag_returned_to_warehouse',
  'audit:bigbag_warehouse_weight_recorded',
  'audit:operator_shift_opened',
  'audit:operator_shift_bag_added',
  'audit:operator_shift_bag_released',
  'audit:operator_shift_closed',
  'problem:operator_reported',
  'problem:shift_balance_mismatch',
  'problem:operator_defect_reported',
  'notification:production_problem_received',
  'audit:roll_deferred',
  'audit:roll_resumed',
  'audit:roll_assignment_released',
  'audit:defect_resolved_rework',
  'audit:defect_resolved_writeoff',
  'audit:production_problem_resolved',

  // warehouse / inventory
  'audit:warehouse_coverage_calculated',
  'audit:warehouse_coverage_decided',
  'audit:warehouse_coverage_recheck_requested',
  'audit:warehouse_roll_coverage_fact_corrected',
  'audit:warehouse_coverage_recheck_resolved',
  'audit:warehouse_coverage_reserved',
  'audit:warehouse_coverage_reservation_cancelled',
  'audit:warehouse_coverage_order_spec_invalidated',
  'audit:warehouse_cover_recheck_requested',
  'audit:warehouse_cover_proposed',
  'audit:warehouse_cover_confirmed',
  'audit:warehouse_cover_commercial_approved',
  'audit:warehouse_cover_technical_approved',
  'audit:warehouse_rolls_reserved_for_order',
  'audit:warehouse_cover_disputed',
  'audit:warehouse_recheck_resolved',
  'audit:warehouse_cover_recalculated',
  'audit:warehouse_cover_rejected',
  'audit:warehouse_cover_forced_production',
  'audit:commercial_warehouse_cover_route_selected',
  'audit:warehouse_delivery_task_created',
  'audit:warehouse_delivery_task_extended',
  'audit:roll_reserved_for_order',
  'audit:roll_reservation_released',
  'audit:finished_stock_created',
  'audit:finished_stock_released_from_cancelled_order',
  'audit:finished_stock_reserved',
  'audit:finished_stock_reservation_released',
  'audit:warehouse_roll_received',
  'audit:warehouse_roll_shipped',
  'audit:defect_bag_received',
  'audit:defect_bag_shipped',
  'audit:warehouse_post_bound',
  'audit:warehouse_control_weight_recorded',
  'audit:warehouse_control_weight_failed',
  'audit:warehouse_reserve_roll_verified',
  'audit:warehouse_acceptance_task_closed',
  'audit:warehouse_physical_operation_expired',
  'audit:warehouse_physical_operation_recovered',
  'audit:warehouse_roll_reserved_overweight',
  'problem:warehouse_defect_reported',
  'audit:warehouse_roll_defect_recycled',
  'audit:warehouse_pallet_opened',
  'audit:warehouse_pallet_sealed',
  'audit:warehouse_pallet_order_mismatch_rejected',
  'audit:warehouse_pallet_cutover_applied',
  'audit:warehouse_pallet_roll_selected',
  'audit:warehouse_pallet_roll_deselected',
  'audit:warehouse_pallet_voided',
  'audit:warehouse_pallet_handoff_scanned',
  'audit:warehouse_pallet_delivery_scanned',
  'audit:pallet_label_layout_published',
  'audit:pallet_list_created',
  'audit:pallet_list_voided',
  'audit:pallet_list_print_requested',
  'audit:pallet_list_print_submitted',
  'audit:pallet_list_print_failed',
  'audit:pallet_list_print_delivery_unknown',
  'audit:pallet_list_print_reconciled',
  'audit:pallet_list_reprint_requested',
  'audit:pallet_list_exported',
  'audit:raw_material_received',
  'audit:inventory_manual_correction',
  'audit:inventory_fact_overrode_accounting_snapshot',
  'problem:inventory_source_conflict',
  'problem:raw_material_shortage',
  'audit:raw_material_shortage_resolved',
  'audit:material_cost_reference_updated',
  'audit:additional_production_cost_recorded',
  'audit:spool_price_reference_recorded',
  'audit:spool_stock_receipt_recorded',
  'audit:roll_production_cost_snapshotted',
  'audit:roll_production_cost_corrected',
  'problem:material_cost_basis_unknown',
  'audit:commercial_order_ready_for_shipment',

  // finance / director / admin
  'audit:finance_order_created',
  'audit:finance_production_cleared',
  'audit:payment_status_updated',
  'audit:manual_payment_corrected',
  'audit:commercial_order_locked_by_payment',
  'audit:invoice_status_updated',
  'audit:payment_status_imported',
  'audit:cash_operation_recorded',
  'audit:installment_plan_created',
  'audit:installment_plan_updated',
  'audit:deferred_payment_terms_selected',
  'audit:deferred_payment_terms_updated',
  'audit:payment_policy_created',
  'audit:payment_policy_updated',
  'audit:deferred_payment_due_scheduled',
  'audit:payment_schedule_item_confirmed',
  'problem:payment_overdue',
  'problem:payment_sync_error',
  'audit:sync_retry_requested',
  'audit:director_finance_override_requested',
  'audit:director_finance_override_applied',
  'audit:director_production_override_applied',
  'audit:director_warehouse_override_applied',
  'audit:director_decision_resolved',
  'audit:penalty_created',
  'notification:penalty_created',
  'audit:payroll_tariff_order_created',
  'audit:payroll_tariff_order_draft_updated',
  'audit:payroll_tariff_order_published',
  'audit:pilot_demo_reset',
  'admin.device.test_requested',
  'admin.user.created',
  'admin.user.profile_updated',
  'admin.user.blocked',
  'admin.user.reactivated',
  'admin.user.password_reset',
  'admin.user.access_updated',
  'admin.access_template.created',
  'admin.access_template.updated',
  'admin.onec.check_requested',
  'admin.onec.import_requested',
  'admin.onec.retry_requested',
  'audit:onec_sync_previewed',
  'audit:onec_sync_started',
  'audit:onec_sync_completed',
  'audit:onec_sync_partial',
  'audit:onec_sync_failed',
  'problem:onec_mapping_conflict',
  'audit:onec_binding_corrected',
  'admin.device.created',
  'admin.device.updated',
  'admin.device.bound',
  'admin.device.recovery_requested',
  'admin.post.created',
  'admin.post.updated',
  'admin.post.token_rotated',
  'admin.platform.check_requested',
  'admin.incident.opened',
  'admin.incident.acknowledged',
  'admin.incident.resolved',
  'admin.incident.reopened',
  'integration.finance_sync_failed',
  'integration.onec_imported',
  'integration.onec_import_failed',
  'integration.onec_sync_started',
  'integration.onec_sync_completed',
  'integration.onec_sync_partial',
  'integration.onec_sync_failed',

  // auth / identity (V2 S1)
  'audit:auth_login',
  'audit:auth_logout',
  'audit:auth_login_failed',
  'audit:session_revoked',
  'audit:password_changed',

  // operator post-session (V2 S3)
  'audit:operator_post_session_opened',
  'audit:operator_post_session_closed',

  // gateway (V2 S4)
  'gateway:post_online',
  'gateway:device_status_changed',
  'gateway:command_completed',
  'gateway:command_recovered',
  'gateway:command_result_conflict',
] as const;

export type DomainEventName = (typeof DOMAIN_EVENTS)[number];

/** Source snapshot kinds — ТЗ §8. Raw payloads are admin-diagnostics only. */
export const SOURCE_KINDS = ['1C', 'mock_1C', 'manual_platform', 'warehouse_runtime'] as const;
export type SourceKind = (typeof SOURCE_KINDS)[number];

/** Payment operation types — ТЗ §5.5 PaymentOperation. */
export const PAYMENT_OPERATION_TYPES = [
  'invoice',
  'cash',
  'cash_to_non_cash',
  'manual_adjustment',
  'unknown',
] as const;
export type PaymentOperationType = (typeof PAYMENT_OPERATION_TYPES)[number];

/** Derive the family ("audit" | "problem" | ...) from an event name. */
export function eventFamily(name: string): EventFamily | undefined {
  const head = name.split(/[:.]/)[0] as EventFamily;
  return EVENT_FAMILIES.includes(head) ? head : undefined;
}
