import { addIcons } from '@siemens/ix-icons';
import {
  iconAdd,
  iconAddCircle,
  iconAppDocumentFilled,
  iconBoxClosed,
  iconBoxOpen,
  iconCalendar,
  iconCapacityCheck,
  iconCheck,
  iconCheckOut,
  iconChevronLeftSmall,
  iconChevronRightSmall,
  iconCloudSuccess,
  iconClose,
  iconContextMenu,
  iconEditDocument,
  iconFactoryReset,
  iconGaugechart,
  iconHand,
  iconHistory,
  iconHistoryList,
  iconInfo,
  iconLockKey,
  iconNetworkDevice,
  iconPackage,
  iconPlantUser,
  iconPlayStepwiseFilled,
  iconPrint,
  iconProjectNew,
  iconQrCode,
  iconReorder,
  iconRulesFilled,
  iconSaveAll,
  iconScale,
  iconSearch,
  iconShieldCheck,
  iconStop,
  iconTableSettings,
  iconTableTag,
  iconTasksOpen,
  iconTrashcan,
  iconTruck,
  iconUserManagementSettingsFilled,
  iconWarning,
  iconWarningRhomb,
  iconWarningSquare,
} from '@siemens/ix-icons/icons';

export const PLENKA_ICONS = {
  iconAdd,
  iconAddCircle,
  iconAppDocumentFilled,
  iconBoxClosed,
  iconBoxOpen,
  iconCalendar,
  iconCapacityCheck,
  iconCheck,
  iconCheckOut,
  iconChevronLeftSmall,
  iconChevronRightSmall,
  iconCloudSuccess,
  iconClose,
  iconContextMenu,
  iconEditDocument,
  iconFactoryReset,
  iconGaugechart,
  iconHand,
  iconHistory,
  iconHistoryList,
  iconInfo,
  iconLockKey,
  iconNetworkDevice,
  iconPackage,
  iconPlantUser,
  iconPlayStepwiseFilled,
  iconPrint,
  iconProjectNew,
  iconQrCode,
  iconReorder,
  iconRulesFilled,
  iconSaveAll,
  iconScale,
  iconSearch,
  iconShieldCheck,
  iconStop,
  iconTableSettings,
  iconTableTag,
  iconTasksOpen,
  iconTrashcan,
  iconTruck,
  iconUserManagementSettingsFilled,
  iconWarning,
  iconWarningRhomb,
  iconWarningSquare,
} as const;

let registered = false;

export function registerPlenkaIcons(): void {
  if (registered) return;
  addIcons(PLENKA_ICONS);
  registered = true;
}
