import type {
  LegacyPalletLabelLayout,
  PalletLabelEditorBootstrap,
} from './palletLabelLayoutModel';

export const legacyLayoutFixture: LegacyPalletLabelLayout = {
  schemaVersion: 1,
  profile: 'pallet-100x100-configurable-v7',
  elements: [
    {
      id: 'header',
      kind: 'text',
      xDots: 36,
      yDots: 32,
      widthDots: 728,
      heightDots: 48,
      maxFontSize: 34,
      minFontSize: 22,
      locked: false,
    },
    {
      id: 'identity',
      kind: 'text',
      xDots: 36,
      yDots: 92,
      widthDots: 390,
      heightDots: 74,
      maxFontSize: 22,
      minFontSize: 12,
      locked: false,
    },
    {
      id: 'product',
      kind: 'text',
      xDots: 36,
      yDots: 170,
      widthDots: 390,
      heightDots: 140,
      maxFontSize: 23,
      minFontSize: 12,
      locked: false,
    },
    {
      id: 'rollCodes',
      kind: 'list',
      xDots: 36,
      yDots: 320,
      widthDots: 390,
      heightDots: 236,
      maxFontSize: 16,
      minFontSize: 9,
      locked: false,
    },
    {
      id: 'qr',
      kind: 'qr',
      xDots: 449,
      yDots: 92,
      widthDots: 315,
      heightDots: 315,
      maxFontSize: 0,
      minFontSize: 0,
      locked: true,
    },
    {
      id: 'summary',
      kind: 'text',
      xDots: 449,
      yDots: 415,
      widthDots: 315,
      heightDots: 141,
      maxFontSize: 15,
      minFontSize: 8,
      locked: false,
    },
    {
      id: 'packaging',
      kind: 'text',
      xDots: 36,
      yDots: 594,
      widthDots: 728,
      heightDots: 28,
      maxFontSize: 15,
      minFontSize: 11,
      locked: false,
    },
    {
      id: 'storage',
      kind: 'text',
      xDots: 36,
      yDots: 628,
      widthDots: 728,
      heightDots: 128,
      maxFontSize: 14,
      minFontSize: 11,
      locked: false,
    },
  ],
};

export const bootstrapFixture: PalletLabelEditorBootstrap = {
  schemaVersion: 2,
  profile: 'pallet-100x100-configurable-v7',
  canvas: {
    widthDots: 800,
    heightDots: 800,
    dotsPerMm: 8,
    safeInsetDots: 20,
    provenCutYDots: 570,
  },
  editorLayout: {
    schemaVersion: 2,
    profile: 'pallet-100x100-configurable-v7',
    elements: [
      {
        id: 'order',
        kind: 'text',
        xDots: 36,
        yDots: 36,
        widthDots: 390,
        heightDots: 62,
        maxFontSize: 30,
        minFontSize: 18,
        locked: false,
      },
      {
        id: 'customer',
        kind: 'text',
        xDots: 36,
        yDots: 110,
        widthDots: 390,
        heightDots: 88,
        maxFontSize: 28,
        minFontSize: 16,
        locked: false,
      },
      {
        id: 'formedAt',
        kind: 'text',
        xDots: 36,
        yDots: 210,
        widthDots: 390,
        heightDots: 62,
        maxFontSize: 24,
        minFontSize: 14,
        locked: false,
      },
      {
        id: 'rollCount',
        kind: 'text',
        xDots: 36,
        yDots: 284,
        widthDots: 390,
        heightDots: 62,
        maxFontSize: 30,
        minFontSize: 18,
        locked: false,
      },
      {
        id: 'qr',
        kind: 'qr',
        xDots: 449,
        yDots: 36,
        widthDots: 315,
        heightDots: 315,
        maxFontSize: 0,
        minFontSize: 0,
        locked: true,
      },
      {
        id: 'storage',
        kind: 'text',
        xDots: 36,
        yDots: 380,
        widthDots: 728,
        heightDots: 170,
        maxFontSize: 28,
        minFontSize: 16,
        locked: false,
      },
    ],
  },
  activePublication: null,
  sources: [
    {
      documentId: 'pllsrc_ctl_1e807e96d0c94b34a5df98cc0ecf4206',
      kind: 'control',
      label: 'Контрольный синтетический источник',
      palletId: 'CONTROL-VALIDATION-01',
      createdAt: '2026-01-01T00:00:00.000Z',
      rollCount: 24,
    },
  ],
};
