import type { PermissionCapability, Role, RoleAccessPolicy } from './types';
import { WAREHOUSE_VISIBLE_SECTIONS } from './warehouseSections';
import { FINANCE_SECTIONS } from './financeSections';

export const hasEffectiveCapability = (
  capabilities: readonly string[] | null | undefined,
  capability: string,
) => capabilities?.includes(capability) ?? false;

export const roleAccessPolicies: Record<Role, RoleAccessPolicy> = {
  commercial: {
    role: 'commercial',
    seniorAccessScope: 'senior_commercial',
    visibleSections: [
      'Входящие заявки',
      'Черновики',
      'В работе',
      'Выполненные',
      'Сырьё',
      'Проблемы',
      'Контроль',
      'Финансы',
      'Производство',
      'Склад',
    ],
    hiddenScopes: ['operator', 'warehouse', 'rawDiagnostics', 'sensitiveFinance'],
    capabilities: [
      'commercial.view',
      'commercial.manage',
      'business_performance.view_safe',
      'finance.view_safe',
      'production.view',
      'warehouse.view',
      'raw_material.view_summary',
      'raw_material.view_usage',
      'raw_material.view_accounting_reference',
      'material_cost.view',
      'audit.view',
    ],
    accessSummary: [
      'Доступ: заявки, производство, оплата и отгрузка',
      'Оплату и служебную диагностику изменить нельзя',
    ],
  },
  production: {
    role: 'production',
    seniorAccessScope: 'none',
    visibleSections: [
      'Заказ-наряды',
      'Все рулоны',
      'Операторы / загрузка',
      'Проблемы',
      'Контрагенты и шаблоны',
      'Сырье',
      'Штрафы',
    ],
    hiddenScopes: ['sensitiveFinance', 'warehouse', 'rawDiagnostics'],
    capabilities: [
      'production.view',
      'production.mutate',
      'warehouse.view',
      'qr.history.view',
      'qr.reprint_with_reason',
      'raw_material.view_summary',
      'raw_material.view_usage',
      'raw_material.view_accounting_reference',
      'material_cost.view',
      'audit.view',
      'penalty.create',
    ],
    accessSummary: [
      'Видит заказ-наряд, рецептуру, материалы и блокировки',
      'Не видит откаты и действия оплаты',
    ],
  },
  finance: {
    role: 'finance',
    seniorAccessScope: 'none',
    visibleSections: [...FINANCE_SECTIONS],
    hiddenScopes: ['operator', 'warehouse', 'recipeAnalytics', 'rawDiagnostics'],
    capabilities: [
      'finance.view_full',
      'finance.mutate',
      'raw_material.view_summary',
      'raw_material.view_accounting_reference',
      'material_cost.view',
      'material_cost.edit',
      'audit.view',
      'qr.history.view',
    ],
    accessSummary: [
      'Доступ: счета с оплатами, рассрочки, сырьё и просрочки',
      'Нет доступа к операциям склада и производства',
    ],
  },
  director: {
    role: 'director',
    seniorAccessScope: 'supervisor_override',
    visibleSections: [
      'Контроль',
      'Финансы',
      'Производство',
      'Зарплаты',
      'Проблемы',
      'Склад',
      'Все рулоны',
      'Сырье',
      'Штрафы',
      'Аудит / QR',
    ],
    hiddenScopes: ['rawDiagnostics'],
    capabilities: [
      'commercial.view',
      'business_performance.view_safe',
      'finance.view_full',
      'finance.override',
      'production.view',
      'production.override',
      'warehouse.view',
      'warehouse.override',
      'qr.history.view',
      'raw_material.view_summary',
      'raw_material.view_usage',
      'raw_material.view_accounting_reference',
      'material_cost.view',
      'material_cost.override',
      'audit.view_full',
      'sensitive_finance.view',
      'penalty.view',
      'penalty.create',
    ],
    accessSummary: [
      'Видит деньги, производство, склад, QR, штрафы и закрытые финансы по директорской политике',
      'Может записывать ручное решение с причиной, но не выполняет действия склада, производства, устройств или администрирования',
    ],
  },
  operator: {
    role: 'operator',
    seniorAccessScope: 'none',
    visibleSections: [
      'Рулоны и заказы',
      'Смена',
      'Зарплата',
      'Штрафы',
      'Отложены',
      'Переданы на склад',
    ],
    hiddenScopes: [
      'finance',
      'director',
      'sensitiveFinance',
      'legal',
      'warehouse',
      'rawDiagnostics',
    ],
    capabilities: [
      'operator.execute',
      'operator.payroll.view_self',
      'qr.print',
      'qr.scan',
      'qr.reprint_with_reason',
      'audit.view',
    ],
    accessSummary: [
      'Видит текущую задачу, шаг, вес, QR, устройства и только свои начисления',
      'Не видит счет, оплату, откаты, учетные источники и юридическое имя клиента',
    ],
  },
  warehouse: {
    role: 'warehouse',
    seniorAccessScope: 'none',
    visibleSections: [...WAREHOUSE_VISIBLE_SECTIONS],
    hiddenScopes: [
      'finance',
      'director',
      'sensitiveFinance',
      'legal',
      'recipeAnalytics',
      'rawDiagnostics',
    ],
    capabilities: [
      'warehouse.view',
      'warehouse.scan',
      'qr.scan',
      'qr.reprint_with_reason',
      'qr.history.view',
      'raw_material.view_summary',
      'raw_material.view_usage',
      'raw_material.mutate_stock',
      'raw_material.view_accounting_reference',
      'audit.view',
    ],
    accessSummary: [
      'Видит приемку, выдачу, сырье, склад рулонов и запас/резерв',
      'Не видит финансы, откаты и директорскую аналитику рецептуры',
    ],
  },
  admin: {
    role: 'admin',
    seniorAccessScope: 'none',
    visibleSections: [
      'Доступы',
      'Шаблоны ролей',
      'Устройства',
      'Посты',
      'Макет палетного листа',
      'Виды сырья',
      'Состояние платформы',
      'Инциденты',
      'Проблемы / история',
    ],
    hiddenScopes: [],
    capabilities: [
      'admin.raw_diagnostics',
      'admin.access_manage',
      'pallet_label_layout:manage',
      'device.recover',
      'raw_material.view_summary',
      'material_cost.source_config',
      'audit.view_full',
    ],
    accessSummary: [
      'Доступ: аккаунты, посты, устройства и инциденты',
      'Производственные операции недоступны',
    ],
  },
};

export function getRoleAccessPolicy(role: Role) {
  return roleAccessPolicies[role];
}

export function roleHasCapability(role: Role, capability: PermissionCapability) {
  return getRoleAccessPolicy(role).capabilities.includes(capability);
}
