import type { DomainEventName, Role, RoleInboxCtaKind, RoleInboxSeverity } from '@plenka/contracts';

export type RoleInboxPresentation = {
  eventType: DomainEventName;
  recipientRole: Role;
  nextOwnerRole: Role;
  severity: RoleInboxSeverity;
  title: string;
  body: string;
  cta: {
    kind: RoleInboxCtaKind;
    section: string;
  };
};

const RELATED_ROLE_ROUTES: Record<
  Exclude<Role, 'admin'>,
  { kind: RoleInboxCtaKind; section: string }
> = {
  commercial: { kind: 'commercial_order', section: 'В работе' },
  production_lead: { kind: 'production_order', section: 'Проблемы' },
  operator: { kind: 'operator_roll', section: 'Рулоны и заказы' },
  warehouse: { kind: 'warehouse_intake', section: 'Приемка' },
  finance: { kind: 'finance_order', section: 'Обзор' },
  director: { kind: 'director_decision', section: 'Требуют решения' },
};

function relatedAlert(
  eventType: DomainEventName,
  recipientRole: Exclude<Role, 'admin'>,
  severity: RoleInboxSeverity,
  title: string,
  body: string,
  cta = RELATED_ROLE_ROUTES[recipientRole],
): RoleInboxPresentation {
  return {
    eventType,
    recipientRole,
    nextOwnerRole: recipientRole,
    severity,
    title,
    body,
    cta,
  };
}

const RELATED_ALERT_PRESENTATIONS: readonly RoleInboxPresentation[] = [
  relatedAlert(
    'notification:commercial_order_amended',
    'finance',
    'info',
    'Данные заявки изменены',
    'Коммерция изменила данные заявки. Проверьте актуальный финансовый маршрут.',
  ),
  relatedAlert(
    'notification:commercial_order_amended',
    'production_lead',
    'warning',
    'Данные заказа изменены',
    'Коммерция изменила данные заказа. Проверьте актуальное производственное задание.',
  ),
  relatedAlert(
    'notification:commercial_order_amended',
    'warehouse',
    'warning',
    'Состав заказа изменён',
    'Проверьте актуальность складского покрытия и связанных резервов.',
    { kind: 'warehouse_cover', section: 'Запасы / резерв' },
  ),
  ...(
    [
      [
        'notification:commercial_order_cancelled',
        'Оставшаяся работа по заказу отменена',
        'Отмена заказа зафиксирована',
      ],
      [
        'notification:commercial_order_reactivated',
        'Оставшаяся работа по заказу возобновлена',
        'Возобновление заказа зафиксировано',
      ],
    ] as const
  ).flatMap(([eventType, title, action]) => [
    relatedAlert(
      eventType,
      'commercial',
      'info',
      title,
      `${action}. Проверьте актуальный состав и выполненный объём.`,
    ),
    relatedAlert(
      eventType,
      'production_lead',
      'warning',
      title,
      `${action}. Проверьте только актуальные будущие производственные задания.`,
    ),
    relatedAlert(
      eventType,
      'finance',
      'warning',
      title,
      `${action}. Счёт и оплаты сохранены; при необходимости оформите отдельный перерасчёт.`,
    ),
    relatedAlert(
      eventType,
      'warehouse',
      'warning',
      title,
      `${action}. Проверьте актуальные резервы и складское покрытие.`,
      { kind: 'warehouse_cover', section: 'Запасы / резерв' },
    ),
  ]),
  relatedAlert(
    'problem:operator_defect_reported',
    'operator',
    'critical',
    'Брак по назначенному рулону',
    'Брак зафиксирован. Используйте только актуальное состояние назначенного рулона.',
  ),
  relatedAlert(
    'problem:operator_defect_reported',
    'director',
    'critical',
    'Оператор сообщил о браке',
    'Производственный брак требует контроля связанного решения.',
  ),
  relatedAlert(
    'problem:production_defect_reported',
    'operator',
    'critical',
    'Брак по назначенному рулону',
    'Производство зафиксировало брак. Проверьте актуальное назначение.',
  ),
  relatedAlert(
    'problem:production_defect_reported',
    'director',
    'critical',
    'Производство зафиксировало брак',
    'Проверьте состояние связанного производственного решения.',
  ),
  relatedAlert(
    'problem:warehouse_defect_reported',
    'operator',
    'critical',
    'Склад выявил дефект рулона',
    'Проверьте актуальное состояние только назначенного вам рулона.',
  ),
  relatedAlert(
    'problem:warehouse_defect_reported',
    'warehouse',
    'critical',
    'На приёмке выявлен дефект',
    'Проверьте связанный рулон и ожидайте производственного решения.',
  ),
  relatedAlert(
    'problem:warehouse_defect_reported',
    'director',
    'critical',
    'Склад выявил дефект',
    'Дефект принятого рулона требует контроля решения.',
  ),
  relatedAlert(
    'problem:machine_breakdown_reported',
    'director',
    'critical',
    'Зафиксирована поломка станка',
    'Проверьте производственную блокировку и назначенное решение.',
  ),
  relatedAlert(
    'problem:shift_balance_mismatch',
    'director',
    'critical',
    'Баланс смены не сошёлся',
    'Проверьте производственное расхождение и назначенное решение.',
  ),
  ...(
    [
      ['notification:operator_machine_change_requested', 'Запрошена смена станка'],
      ['notification:operator_machine_change_ready', 'Смена станка готова к продолжению'],
      ['notification:operator_machine_change_completed', 'Смена станка завершена'],
    ] as const
  ).flatMap(([eventType, title]) => [
    relatedAlert(
      eventType,
      'operator',
      'warning',
      title,
      'Проверьте состояние своей смены и выполните доступный следующий шаг.',
      { kind: 'operator_queue', section: 'Смена' },
    ),
    relatedAlert(
      eventType,
      'production_lead',
      'warning',
      title,
      'Проверьте состояние преднамеренной смены рабочего поста.',
    ),
    relatedAlert(
      eventType,
      'director',
      'info',
      title,
      'Состояние преднамеренной смены рабочего поста обновлено.',
    ),
  ]),
  relatedAlert(
    'notification:operator_machine_change_cancelled',
    'operator',
    'info',
    'Смена станка отменена',
    'Продолжайте работу на текущем посту по актуальной очереди.',
    { kind: 'operator_queue', section: 'Смена' },
  ),
  relatedAlert(
    'notification:operator_machine_change_cancelled',
    'production_lead',
    'info',
    'Смена станка отменена',
    'Назначение и активный пост сохранены; проверьте актуальный план смены.',
  ),
  relatedAlert(
    'audit:director_finance_override_applied',
    'finance',
    'warning',
    'Финансовое решение изменено директором',
    'Проверьте актуальный финансовый следующий шаг.',
  ),
  relatedAlert(
    'audit:director_finance_override_applied',
    'director',
    'info',
    'Финансовое решение применено',
    'Директорское решение зафиксировано в истории.',
  ),
  relatedAlert(
    'audit:director_production_override_applied',
    'production_lead',
    'warning',
    'Производственное решение изменено директором',
    'Проверьте актуальный производственный следующий шаг.',
  ),
  relatedAlert(
    'audit:director_production_override_applied',
    'director',
    'info',
    'Производственное решение применено',
    'Директорское решение зафиксировано в истории.',
  ),
  relatedAlert(
    'audit:director_warehouse_override_applied',
    'warehouse',
    'warning',
    'Складское решение изменено директором',
    'Проверьте актуальный складской следующий шаг.',
  ),
  relatedAlert(
    'audit:director_warehouse_override_applied',
    'director',
    'info',
    'Складское решение применено',
    'Директорское решение зафиксировано в истории.',
  ),
  relatedAlert(
    'audit:inventory_manual_correction',
    'warehouse',
    'warning',
    'Складской факт скорректирован',
    'Проверьте актуальное количество и основание корректировки.',
  ),
  relatedAlert(
    'audit:inventory_manual_correction',
    'director',
    'warning',
    'Выполнена ручная складская корректировка',
    'Проверьте основание изменения складского факта.',
  ),
  ...(
    [
      ['audit:replacement_roll_created', 'Создан замещающий рулон'],
      ['audit:defect_resolved_rework', 'Брак направлен на переработку'],
      ['audit:defect_resolved_writeoff', 'Брак списан'],
    ] as const
  ).flatMap(([eventType, title]) => [
    relatedAlert(
      eventType,
      'operator',
      'warning',
      title,
      'Проверьте актуальное состояние только назначенной вам работы.',
    ),
    relatedAlert(
      eventType,
      'production_lead',
      'warning',
      title,
      'Производственное решение по браку обновлено.',
    ),
    relatedAlert(
      eventType,
      'warehouse',
      'warning',
      title,
      'Проверьте актуальное складское действие по связанному рулону.',
    ),
    relatedAlert(
      eventType,
      'director',
      'info',
      title,
      'Решение по производственному браку зафиксировано.',
    ),
  ]),
  relatedAlert(
    'audit:operator_physical_operation_recovered',
    'operator',
    'info',
    'Операция оператора восстановлена',
    'Проверьте восстановленное состояние назначенной работы.',
    { kind: 'operator_queue', section: 'Рулоны и заказы' },
  ),
  relatedAlert(
    'audit:operator_physical_operation_recovered',
    'production_lead',
    'info',
    'Операция оператора восстановлена',
    'Физическая операция восстановлена после ошибки.',
  ),
  relatedAlert(
    'audit:warehouse_physical_operation_recovered',
    'warehouse',
    'info',
    'Складская операция восстановлена',
    'Проверьте восстановленное состояние складской операции.',
  ),
  relatedAlert(
    'audit:warehouse_physical_operation_recovered',
    'production_lead',
    'info',
    'Складская операция восстановлена',
    'Физическая складская операция восстановлена после ошибки.',
  ),
];

export const ROLE_INBOX_PRESENTATIONS: readonly RoleInboxPresentation[] = [
  ...RELATED_ALERT_PRESENTATIONS,
  {
    eventType: 'audit:warehouse_coverage_calculated',
    recipientRole: 'finance',
    nextOwnerRole: 'finance',
    severity: 'info',
    title: 'Покрытие заказа рассчитано',
    body: 'Система рассчитала доступность складского покрытия. Выберите маршрут заказа.',
    cta: { kind: 'finance_order', section: 'Обзор' },
  },
  {
    eventType: 'audit:warehouse_coverage_recheck_requested',
    recipientRole: 'warehouse',
    nextOwnerRole: 'warehouse',
    severity: 'warning',
    title: 'Требуется перепроверка покрытия',
    body: 'Бухгалтерия запросила проверку конкретных фактов складского покрытия.',
    cta: { kind: 'warehouse_cover', section: 'Запасы / резерв' },
  },
  {
    eventType: 'audit:warehouse_coverage_recheck_resolved',
    recipientRole: 'finance',
    nextOwnerRole: 'finance',
    severity: 'info',
    title: 'Перепроверка покрытия завершена',
    body: 'Склад обновил факты покрытия. Проверьте новый расчёт и выберите маршрут.',
    cta: { kind: 'finance_order', section: 'Обзор' },
  },
  {
    eventType: 'audit:invoice_handoff_created',
    recipientRole: 'finance',
    nextOwnerRole: 'finance',
    severity: 'info',
    title: 'Новая заявка на счёт',
    body: 'Коммерция передала заявку для выставления счёта.',
    cta: { kind: 'finance_order', section: 'Обзор' },
  },
  {
    eventType: 'audit:finance_order_created',
    recipientRole: 'finance',
    nextOwnerRole: 'finance',
    severity: 'info',
    title: 'Заявка принята в финансовый контур',
    body: 'Откройте заявку и проверьте условия выставления счёта.',
    cta: { kind: 'finance_order', section: 'Обзор' },
  },
  {
    eventType: 'audit:finance_order_created',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Заявка принята бухгалтерией',
    body: 'Финансовый контур принял заявку в работу.',
    cta: { kind: 'commercial_order', section: 'В работе' },
  },
  {
    eventType: 'audit:invoice_status_updated',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Счёт выставлен',
    body: 'Бухгалтерия зафиксировала счёт. Проверьте следующий шаг по заявке.',
    cta: { kind: 'commercial_order', section: 'В работе' },
  },
  {
    eventType: 'audit:payment_status_updated',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Статус оплаты обновлён',
    body: 'Проверьте финансовый допуск и следующий шаг по заявке.',
    cta: { kind: 'commercial_order', section: 'В работе' },
  },
  {
    eventType: 'audit:payment_schedule_item_confirmed',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Платёж подтверждён',
    body: 'Проверьте допуск и при готовности передайте заявку в производство.',
    cta: { kind: 'commercial_order', section: 'В работе' },
  },
  {
    eventType: 'audit:production_order_created',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'info',
    title: 'Новый заказ-наряд',
    body: 'Коммерция передала заявку в производство.',
    cta: { kind: 'production_order', section: 'Заказ-наряды' },
  },
  {
    eventType: 'notification:production_order_fully_handed_over',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'info',
    title: 'Заказ полностью передан на склад',
    body: 'Все рулоны заказа переданы на склад. Информация о заказе доступна ниже.',
    cta: { kind: 'production_order', section: 'Заказ-наряды' },
  },
  {
    eventType: 'notification:commercial_correction_applied',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Исправление заказа применено',
    body: 'Параметры заказа обновлены после ошибки. Проверьте следующий шаг заявки.',
    cta: { kind: 'commercial_order', section: 'В работе' },
  },
  {
    eventType: 'notification:commercial_correction_applied',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'warning',
    title: 'Производственные параметры обновлены',
    body: 'Связанная позиция заказа исправлена. Проверьте актуальное задание.',
    cta: { kind: 'production_order', section: 'Заказ-наряды' },
  },
  {
    eventType: 'notification:commercial_correction_applied',
    recipientRole: 'operator',
    nextOwnerRole: 'operator',
    severity: 'warning',
    title: 'Назначенное задание обновлено',
    body: 'Параметры связанного рулона исправлены. Используйте только актуальное задание.',
    cta: { kind: 'operator_roll', section: 'Рулоны и заказы' },
  },
  {
    eventType: 'notification:commercial_correction_applied',
    recipientRole: 'warehouse',
    nextOwnerRole: 'warehouse',
    severity: 'info',
    title: 'Данные связанного заказа обновлены',
    body: 'После ошибки применено исправление. Проверьте актуальные складские действия.',
    cta: { kind: 'warehouse_cover', section: 'Запасы / резерв' },
  },
  {
    eventType: 'notification:commercial_correction_applied',
    recipientRole: 'finance',
    nextOwnerRole: 'finance',
    severity: 'info',
    title: 'Данные заказа обновлены',
    body: 'После ошибки применено исправление. Проверьте финансовый маршрут заказа.',
    cta: { kind: 'finance_order', section: 'Обзор' },
  },
  {
    eventType: 'notification:commercial_correction_applied',
    recipientRole: 'director',
    nextOwnerRole: 'director',
    severity: 'warning',
    title: 'Исправление по заказу применено',
    body: 'Связанная ошибка исправлена. Проверьте состояние исполнения заказа.',
    cta: { kind: 'director_decision', section: 'Требуют решения' },
  },
  {
    eventType: 'audit:task_assigned',
    recipientRole: 'operator',
    nextOwnerRole: 'operator',
    severity: 'info',
    title: 'Назначена новая задача',
    body: 'Проверьте назначенный рулон и рабочий пост.',
    cta: { kind: 'operator_roll', section: 'Рулоны и заказы' },
  },
  {
    eventType: 'audit:task_reassigned',
    recipientRole: 'operator',
    nextOwnerRole: 'operator',
    severity: 'warning',
    title: 'Назначение задачи изменено',
    body: 'Проверьте обновлённое назначение рулона и рабочего поста.',
    cta: { kind: 'operator_roll', section: 'Рулоны и заказы' },
  },
  {
    eventType: 'audit:operator_roll_handed_over',
    recipientRole: 'warehouse',
    nextOwnerRole: 'warehouse',
    severity: 'info',
    title: 'Рулон ожидает приёмки',
    body: 'Оператор передал рулон на склад.',
    cta: { kind: 'warehouse_intake', section: 'Приемка' },
  },
  {
    eventType: 'audit:warehouse_delivery_task_created',
    recipientRole: 'warehouse',
    nextOwnerRole: 'warehouse',
    severity: 'info',
    title: 'Заказ готов к выдаче',
    body: 'Комплектация завершена. Отсканируйте рулоны и закройте выдачу.',
    cta: { kind: 'warehouse_intake', section: 'Выдача' },
  },
  {
    eventType: 'audit:warehouse_cover_recheck_requested',
    recipientRole: 'warehouse',
    nextOwnerRole: 'warehouse',
    severity: 'warning',
    title: 'Требуется проверить покрытие',
    body: 'Коммерция запросила проверку складского покрытия.',
    cta: { kind: 'warehouse_cover', section: 'Запасы / резерв' },
  },
  {
    eventType: 'audit:warehouse_cover_recheck_requested',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Склад перепроверяет покрытие',
    body: 'Запрос на проверку покрытия принят складом.',
    cta: { kind: 'commercial_order', section: 'В работе' },
  },
  {
    eventType: 'audit:warehouse_cover_proposed',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'warning',
    title: 'Склад предложил покрытие',
    body: 'Проверьте предложенные рулоны и выберите дальнейший маршрут.',
    cta: { kind: 'warehouse_cover', section: 'В работе' },
  },
  {
    eventType: 'audit:warehouse_cover_commercial_approved',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'warning',
    title: 'Требуется техническая проверка покрытия',
    body: 'Коммерция подтвердила маршрут покрытия. Проверьте техническую допустимость.',
    cta: { kind: 'warehouse_cover', section: 'Заказ-наряды' },
  },
  {
    eventType: 'audit:warehouse_cover_technical_approved',
    recipientRole: 'warehouse',
    nextOwnerRole: 'warehouse',
    severity: 'info',
    title: 'Покрытие технически подтверждено',
    body: 'Завпроизводства подтвердил выбранный маршрут покрытия.',
    cta: { kind: 'warehouse_cover', section: 'Запасы / резерв' },
  },
  {
    eventType: 'audit:warehouse_cover_technical_approved',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Покрытие технически подтверждено',
    body: 'Маршрут покрытия подтверждён производством.',
    cta: { kind: 'warehouse_cover', section: 'В работе' },
  },
  {
    eventType: 'audit:warehouse_rolls_reserved_for_order',
    recipientRole: 'warehouse',
    nextOwnerRole: 'warehouse',
    severity: 'info',
    title: 'Рулоны зарезервированы',
    body: 'Резерв покрытия создан для заявки.',
    cta: { kind: 'warehouse_cover', section: 'Запасы / резерв' },
  },
  {
    eventType: 'audit:warehouse_rolls_reserved_for_order',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Покрытие зарезервировано',
    body: 'Склад зарезервировал подтверждённые рулоны для заявки.',
    cta: { kind: 'warehouse_cover', section: 'В работе' },
  },
  {
    eventType: 'audit:warehouse_roll_received',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Склад принял рулон',
    body: 'Приёмка рулона завершена; исполнение заявки обновлено.',
    cta: { kind: 'commercial_order', section: 'В работе' },
  },
  {
    eventType: 'audit:warehouse_roll_shipped',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Заказ отгружен',
    body: 'Склад зафиксировал отгрузку по заявке.',
    cta: { kind: 'commercial_order', section: 'Выполненные' },
  },
  {
    eventType: 'audit:warehouse_roll_shipped',
    recipientRole: 'finance',
    nextOwnerRole: 'finance',
    severity: 'info',
    title: 'Заказ отгружен',
    body: 'Склад зафиксировал отгрузку. Проверьте финансовый следующий шаг.',
    cta: { kind: 'finance_order', section: 'Обзор' },
  },
  {
    eventType: 'audit:deferred_payment_due_scheduled',
    recipientRole: 'finance',
    nextOwnerRole: 'finance',
    severity: 'info',
    title: 'Наступил следующий платёжный этап',
    body: 'После отгрузки создана задача по графику оплаты.',
    cta: { kind: 'finance_order', section: 'Оплаты' },
  },
  {
    eventType: 'audit:commercial_order_ready_for_shipment',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'info',
    title: 'Заявка готова к отгрузке',
    body: 'Производственный и складской этапы позволяют перейти к отгрузке.',
    cta: { kind: 'commercial_order', section: 'Выполненные' },
  },
  {
    eventType: 'problem:production_reported_to_commercial',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'warning',
    title: 'Производству нужно решение',
    body: 'Откройте заявку и выберите допустимый следующий шаг.',
    cta: { kind: 'commercial_order', section: 'В работе' },
  },
  {
    eventType: 'problem:raw_material_shortage',
    recipientRole: 'commercial',
    nextOwnerRole: 'commercial',
    severity: 'critical',
    title: 'Не хватает сырья',
    body: 'Требуется решение по сырью для продолжения заявки.',
    cta: { kind: 'commercial_order', section: 'В работе' },
  },
  {
    eventType: 'problem:raw_material_shortage',
    recipientRole: 'director',
    nextOwnerRole: 'director',
    severity: 'critical',
    title: 'Сырьё блокирует выполнение',
    body: 'Проверьте исключение и назначьте ответственное решение.',
    cta: { kind: 'director_decision', section: 'Требуют решения' },
  },
  {
    eventType: 'problem:machine_breakdown_reported',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'critical',
    title: 'Оператор сообщил о поломке',
    body: 'Проверьте станок и переназначьте заблокированную работу.',
    cta: { kind: 'production_order', section: 'Проблемы' },
  },
  {
    eventType: 'problem:production_defect_reported',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'warning',
    title: 'Зафиксирован производственный брак',
    body: 'Откройте проблему и выберите решение по рулону.',
    cta: { kind: 'production_problem', section: 'Проблемы' },
  },
  {
    eventType: 'problem:warehouse_defect_reported',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'warning',
    title: 'Склад сообщил о дефекте',
    body: 'Откройте проблему и выберите решение по принятому рулону.',
    cta: { kind: 'production_problem', section: 'Проблемы' },
  },
  {
    eventType: 'problem:operator_defect_reported',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'warning',
    title: 'Оператор сообщил о дефекте',
    body: 'Откройте проблему и выберите решение по рулону.',
    cta: { kind: 'production_problem', section: 'Проблемы' },
  },
  {
    eventType: 'problem:shift_balance_mismatch',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'critical',
    title: 'Баланс смены не сошёлся',
    body: 'Проверьте расхождение смены до закрытия производственного этапа.',
    cta: { kind: 'production_order', section: 'Проблемы' },
  },
  {
    eventType: 'notification:production_problem_received',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'critical',
    title: 'Производственная проблема требует решения',
    body: 'Откройте проблему и проверьте следующий шаг.',
    cta: { kind: 'production_problem', section: 'Проблемы' },
  },
  ...(
    [
      ['commercial', 'Оператор сообщил о проблеме'],
      ['production_lead', 'Проблема оператора требует решения'],
      ['director', 'Оператор сообщил о производственной проблеме'],
    ] as const
  ).map(
    ([recipientRole, title]): RoleInboxPresentation => ({
      eventType: 'problem:operator_reported',
      recipientRole,
      nextOwnerRole: recipientRole,
      severity: 'warning',
      title,
      body: 'Откройте точную проблему и проверьте следующий рабочий шаг.',
      cta: { kind: 'production_problem', section: 'Проблемы' },
    }),
  ),
  {
    eventType: 'problem:payment_overdue',
    recipientRole: 'finance',
    nextOwnerRole: 'finance',
    severity: 'critical',
    title: 'Платёж просрочен',
    body: 'Проверьте график оплаты и зафиксируйте следующий шаг.',
    cta: { kind: 'finance_order', section: 'Исключения' },
  },
  {
    eventType: 'problem:payment_overdue',
    recipientRole: 'director',
    nextOwnerRole: 'director',
    severity: 'critical',
    title: 'Просрочка требует контроля',
    body: 'Проверьте финансовое исключение и ответственное решение.',
    cta: { kind: 'director_decision', section: 'Требуют решения' },
  },
  {
    eventType: 'problem:payment_sync_error',
    recipientRole: 'finance',
    nextOwnerRole: 'finance',
    severity: 'critical',
    title: 'Ошибка сверки оплаты',
    body: 'Проверьте источник финансовых данных и повторите сверку.',
    cta: { kind: 'finance_order', section: 'Сверка источников' },
  },
  {
    eventType: 'audit:warehouse_cover_disputed',
    recipientRole: 'director',
    nextOwnerRole: 'director',
    severity: 'critical',
    title: 'По покрытию возник конфликт',
    body: 'Проверьте исключение по складскому покрытию и доступное решение.',
    cta: { kind: 'director_decision', section: 'Требуют решения' },
  },
  {
    eventType: 'audit:director_finance_override_requested',
    recipientRole: 'director',
    nextOwnerRole: 'director',
    severity: 'warning',
    title: 'Запрошено финансовое решение',
    body: 'Проверьте основание и примите отдельное директорское решение.',
    cta: { kind: 'director_decision', section: 'Требуют решения' },
  },
  {
    eventType: 'notification:penalty_created',
    recipientRole: 'operator',
    nextOwnerRole: 'operator',
    severity: 'warning',
    title: 'Назначен штраф',
    body: 'Откройте личный журнал штрафов и ознакомьтесь с основанием.',
    cta: { kind: 'penalty', section: 'Штрафы' },
  },
  {
    eventType: 'notification:penalty_created',
    recipientRole: 'production_lead',
    nextOwnerRole: 'production_lead',
    severity: 'warning',
    title: 'Назначен штраф',
    body: 'Откройте журнал штрафов и ознакомьтесь с основанием.',
    cta: { kind: 'penalty', section: 'Штрафы' },
  },
  {
    eventType: 'admin.incident.opened',
    recipientRole: 'admin',
    nextOwnerRole: 'admin',
    severity: 'critical',
    title: 'Открыт технический инцидент',
    body: 'Проверьте инцидент и план восстановления.',
    cta: { kind: 'admin_incident', section: 'Инциденты' },
  },
  {
    eventType: 'admin.incident.reopened',
    recipientRole: 'admin',
    nextOwnerRole: 'admin',
    severity: 'critical',
    title: 'Технический инцидент повторился',
    body: 'Проверьте новый эпизод инцидента и план восстановления.',
    cta: { kind: 'admin_incident', section: 'Инциденты' },
  },
];

const routeKey = (eventType: string, recipientRole: Role) => `${eventType}\u0000${recipientRole}`;

const presentationsByRoute: ReadonlyMap<string, RoleInboxPresentation> = new Map(
  ROLE_INBOX_PRESENTATIONS.map((presentation) => [
    routeKey(presentation.eventType, presentation.recipientRole),
    presentation,
  ]),
);

export function presentationFor(
  eventType: string,
  recipientRole: Role,
): RoleInboxPresentation | undefined {
  return presentationsByRoute.get(routeKey(eventType, recipientRole));
}

export function recipientsFor(eventType: string): Role[] {
  return ROLE_INBOX_PRESENTATIONS.filter(
    (presentation) => presentation.eventType === eventType,
  ).map((presentation) => presentation.recipientRole);
}

export function eventTypesFor(recipientRole: Role): DomainEventName[] {
  return ROLE_INBOX_PRESENTATIONS.filter(
    (presentation) => presentation.recipientRole === recipientRole,
  ).map((presentation) => presentation.eventType);
}
