import { runtimeDeviceMocks } from './adapters';
import type { ProductionRuntimeState } from './types';

export const initialProductionRuntimeState: ProductionRuntimeState = {
  events: [
    {
      id: 'ev-initial-production-recipe',
      family: 'OperationalEvent',
      type: 'production.recipe_change_requires_decision',
      objectId: 'ЗН-2606-014',
      role: 'production',
      label: 'Изменение рецептуры',
      detail: 'Замена сырья влияет на оставшийся рулон; рублевый эффект показывается только с учётным источником или ручным override.',
      createdAt: '10:45',
    },
    {
      id: 'ev-initial-warehouse-partial',
      family: 'ProblemEvent',
      type: 'warehouse.acceptance.partial_marked',
      objectId: 'WH-2606-044',
      role: 'warehouse',
      label: 'Частичная приемка',
      detail: 'Склад принял 2 из 3 рулонов, счетчик недостачи открыт.',
      createdAt: '12:05',
    },
    {
      id: 'ev-initial-finance-due',
      family: 'OperationalEvent',
      type: 'finance.payment_due_today',
      objectId: 'FIN-2606-023',
      role: 'finance',
      label: 'Оплата сегодня',
      detail: 'Нужно выставить или отправить счет к плановой оплате.',
      createdAt: '09:00',
    },
    {
      id: 'ev-initial-master-kpi-candidate',
      family: 'MasterKpiEvent',
      type: 'kpi.quality_output_candidate',
      objectId: 'ROLL-2606-014-03',
      role: 'operator',
      label: 'Факт качества',
      detail: 'Событие доступно как факт, без расчетной формулы.',
      createdAt: '12:40',
    },
  ],
  warehouseAcceptances: [
    {
      id: 'WH-2606-044',
      orderId: 'A-17',
      sourceTaskId: 'OP-A-17',
      handoverId: 'HAND-A-17',
      status: 'partial',
      expectedRollIds: ['R-A17-01', 'R-A17-02', 'R-A17-03'],
      scannedRollIds: ['R-A17-01', 'R-A17-02'],
      acceptedRollIds: ['R-A17-01', 'R-A17-02'],
      missingRollIds: ['R-A17-03'],
      excessPayloads: [],
      lastScan: 'Дубликат R-A17-02',
      scanResult: 'Частичная приемка: не хватает R-A17-03',
      rolls: [
        {
          id: 'R-A17-01',
          sequenceNumber: 1,
          status: 'accepted',
          filmType: 'рукав',
          micron: '80 мкм',
          sizeMeters: '1200 м x 1.2 м',
          plannedNetKg: 41.2,
          tolerancePercent: 2,
          qrCode: 'QR-R-A17-01',
        },
        {
          id: 'R-A17-02',
          sequenceNumber: 2,
          status: 'accepted',
          filmType: 'рукав',
          micron: '80 мкм',
          sizeMeters: '1200 м x 1.2 м',
          plannedNetKg: 41.2,
          tolerancePercent: 2,
          qrCode: 'QR-R-A17-02',
        },
        {
          id: 'R-A17-03',
          sequenceNumber: 3,
          status: 'missing',
          filmType: 'рукав',
          micron: '80 мкм',
          sizeMeters: '900 м x 1.2 м',
          plannedNetKg: 36.8,
          tolerancePercent: 2,
          qrCode: 'QR-R-A17-03',
        },
      ],
      rollGroups: [],
      createdAt: '12:05',
    },
  ],
  deliveries: [],
  paymentTriggers: [],
  problems: [
    {
      id: 'pr-initial-production-recipe',
      objectId: 'DIR-2606-006',
      scope: 'material',
      title: 'Изменение рецептуры',
      severity: 'warning',
      ownerRole: 'Директор',
      reason: 'М1 -> М2, рулон 3. Рублевый эффект считается из рецептуры и source-aware price reference.',
      recovery: 'Подтвердить или вернуть.',
      status: 'open',
      createdAt: '10:45',
    },
    {
      id: 'pr-initial-warehouse-partial',
      objectId: 'WH-2606-044',
      scope: 'warehouse',
      title: 'Частичная приемка',
      severity: 'critical',
      ownerRole: 'Директор',
      reason: 'Не хватает R-A17-03.',
      recovery: 'Принять частично или вернуть.',
      status: 'open',
      createdAt: '12:05',
    },
    {
      id: 'pr-initial-finance-overdue',
      objectId: 'FIN-2606-021',
      scope: 'finance',
      title: 'Просрочка оплаты',
      severity: 'critical',
      ownerRole: 'Бухгалтерия',
      reason: 'Просрочка 3 дня.',
      recovery: 'Назначить разбор с бухгалтерией и открыть подтверждения.',
      status: 'open',
      createdAt: '09:15',
    },
  ],
  labelPrintJobs: [],
  defects: [],
  penalties: [
    {
      penaltyId: 'PEN-2606-002',
      employeeId: 'operator-line-a',
      employeeName: 'Сергей Волков',
      employeeRole: 'Оператор',
      targetRole: 'operator',
      scopeObjectId: 'ROLL-2606-014-03',
      reason: 'Недовес рулона выше допуска',
      amountLabel: '2 000 ₽',
      author: 'Директор',
      status: 'notified',
      createdAt: '12:44',
      history: [
        {
          id: 'h-penalty-2606-002-created',
          time: '12:44',
          actorLabel: 'Директор',
          actionLabel: 'audit:penalty_created',
          detail: 'Назначен штраф оператору линии. Причина: недовес рулона выше допуска.',
        },
        {
          id: 'h-penalty-2606-002-notified',
          time: '12:44',
          actorLabel: 'Система',
          actionLabel: 'notification:penalty_sent',
          detail: 'Оператор получил личное уведомление о штрафе.',
        },
      ],
    },
    {
      penaltyId: 'PEN-2606-004',
      employeeId: 'operator-line-a',
      employeeName: 'Сергей Волков',
      employeeRole: 'Оператор',
      targetRole: 'operator',
      scopeObjectId: 'SHIFT-A-2606-16',
      reason: 'Повторная задержка передачи рулона на склад',
      amountLabel: '1 500 ₽',
      author: 'Зав. производства',
      status: 'notified',
      createdAt: '13:20',
      history: [
        {
          id: 'h-penalty-2606-004-created',
          time: '13:20',
          actorLabel: 'Зав. производства',
          actionLabel: 'audit:penalty_created',
          detail: 'Назначен штраф оператору. Причина: задержка передачи рулона на склад.',
        },
        {
          id: 'h-penalty-2606-004-notified',
          time: '13:20',
          actorLabel: 'Система',
          actionLabel: 'notification:penalty_sent',
          detail: 'Оператор получил личное уведомление о штрафе.',
        },
      ],
    },
    {
      penaltyId: 'PEN-2606-005',
      employeeId: 'operator-line-b',
      employeeName: 'Илья Ковалев',
      employeeRole: 'Оператор',
      targetRole: 'operator',
      scopeObjectId: 'QR-R-2606-020-02',
      reason: 'QR-этикетка перепечатана без причины в сменном журнале',
      amountLabel: '1 000 ₽',
      author: 'Зав. производства',
      status: 'notified',
      createdAt: '11:35',
      history: [
        {
          id: 'h-penalty-2606-005-created',
          time: '11:35',
          actorLabel: 'Зав. производства',
          actionLabel: 'audit:penalty_created',
          detail: 'Назначен штраф оператору. Причина: перепечатка QR без причины.',
        },
        {
          id: 'h-penalty-2606-005-notified',
          time: '11:35',
          actorLabel: 'Система',
          actionLabel: 'notification:penalty_sent',
          detail: 'Оператор получил личное уведомление о штрафе.',
        },
      ],
    },
    {
      penaltyId: 'PEN-2606-006',
      employeeId: 'operator-line-d',
      employeeName: 'Андрей Морозов',
      employeeRole: 'Оператор',
      targetRole: 'operator',
      scopeObjectId: 'ROLL-2606-030-01',
      reason: 'Отклонение от инструкции по режиму экструдера',
      amountLabel: '2 500 ₽',
      author: 'Директор',
      status: 'notified',
      createdAt: '10:10',
      history: [
        {
          id: 'h-penalty-2606-006-created',
          time: '10:10',
          actorLabel: 'Директор',
          actionLabel: 'audit:penalty_created',
          detail: 'Назначен штраф оператору. Причина: отклонение от инструкции по режиму экструдера.',
        },
        {
          id: 'h-penalty-2606-006-notified',
          time: '10:10',
          actorLabel: 'Система',
          actionLabel: 'notification:penalty_sent',
          detail: 'Оператор получил личное уведомление о штрафе.',
        },
      ],
    },
    {
      penaltyId: 'PEN-2606-007',
      employeeId: 'operator-line-c',
      employeeName: 'Максим Лебедев',
      employeeRole: 'Оператор',
      targetRole: 'operator',
      scopeObjectId: 'DEF-R-2606-031-02',
      reason: 'Брак записан после завершения смены',
      amountLabel: '1 200 ₽',
      author: 'Зав. производства',
      status: 'cancelled',
      createdAt: '08:50',
      updatedAt: '09:25',
      history: [
        {
          id: 'h-penalty-2606-007-updated',
          time: '09:25',
          actorLabel: 'Директор',
          actionLabel: 'audit:penalty_updated',
          detail: 'Штраф отменен после сверки audit по смене.',
          oldValue: 'создан',
          newValue: 'отменен',
        },
        {
          id: 'h-penalty-2606-007-created',
          time: '08:50',
          actorLabel: 'Зав. производства',
          actionLabel: 'audit:penalty_created',
          detail: 'Назначен штраф оператору. Причина: поздняя запись брака.',
        },
      ],
    },
    {
      penaltyId: 'PEN-2606-008',
      employeeId: 'production-lead-a',
      employeeName: 'Зав. производства Артур',
      employeeRole: 'Зав. производства',
      targetRole: 'production_lead',
      scopeObjectId: 'ЗН-2606-014',
      reason: 'Не назначен оператор до начала смены',
      amountLabel: '3 000 ₽',
      author: 'Директор',
      status: 'notified',
      createdAt: '09:40',
      history: [
        {
          id: 'h-penalty-2606-008-created',
          time: '09:40',
          actorLabel: 'Директор',
          actionLabel: 'audit:penalty_created',
          detail: 'Назначен штраф зав. производства. Причина: оператор не назначен до начала смены.',
        },
        {
          id: 'h-penalty-2606-008-notified',
          time: '09:40',
          actorLabel: 'Система',
          actionLabel: 'notification:penalty_sent',
          detail: 'Зав. производства получил ограниченное уведомление о штрафе.',
        },
      ],
    },
  ],
  devices: runtimeDeviceMocks,
  commercialDrafts: [],
  orders: [],
  financeOrders: [
    {
      id: 'FIN-RUNTIME-2606-014',
      orderId: 'ЗН-2606-014',
      status: 'waiting_invoice',
      source: 'production_approval',
      counterpartyLabel: 'УралПак',
      amountLabel: '1 284 000 ₽',
      amountPaidLabel: '0 ₽',
      amountRemainingLabel: '1 284 000 ₽',
      createdAt: '10:40',
    },
    {
      id: 'FIN-RUNTIME-2606-020',
      orderId: 'ЗН-2606-020',
      status: 'installment_running',
      source: 'warehouse_delivery',
      paymentTriggerId: 'PAY-2606-020',
      counterpartyLabel: 'ВекторПак',
      amountLabel: '780 000 ₽',
      amountPaidLabel: '0 ₽',
      amountRemainingLabel: '780 000 ₽',
      dueDateLabel: 'через 8 дней',
      createdAt: '11:20',
    },
    {
      id: 'FIN-RUNTIME-2606-021',
      orderId: 'ЗН-2606-021',
      status: 'overdue',
      source: 'warehouse_delivery',
      paymentTriggerId: 'PAY-2606-021',
      counterpartyLabel: 'ПакетПром',
      amountLabel: '420 000 ₽',
      amountPaidLabel: '0 ₽',
      amountRemainingLabel: '420 000 ₽',
      dueDateLabel: 'просрочено 3 дня',
      createdAt: '09:15',
    },
  ],
  directorDecisions: [],
  kickbacks: [],
};
